# Generated by Django 6.0.6 on 2026-06-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Shablon nomi')),
                ('background_image', models.ImageField(upload_to='certificates/templates/', verbose_name='Sertifikat fon rasmi')),
                ('name_x', models.IntegerField(default=400, verbose_name='Ism X koordinatasi')),
                ('name_y', models.IntegerField(default=300, verbose_name='Ism Y koordinatasi')),
                ('name_font_size', models.IntegerField(default=24, verbose_name="Ism shrift o'lchami")),
                ('date_x', models.IntegerField(default=400, verbose_name='Sana X koordinatasi')),
                ('date_y', models.IntegerField(default=450, verbose_name='Sana Y koordinatasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Sertifikat shabloni',
                'verbose_name_plural': 'Sertifikat shablonlari',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name="Bo'lim haqida")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name="E'lon sarlavhasi")),
                ('content', models.TextField(verbose_name="E'lon matni")),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Rasm (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('work_experience', models.CharField(blank=True, max_length=100, verbose_name='Ish staji')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('is_senior', models.BooleanField(default=False, verbose_name='Starshiy xodimmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name="Bo'lim")),
                ('senior_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_employees', to='core.employee', verbose_name='Starshiy xodim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Imtihon nomi')),
                ('exam_date', models.DateField(verbose_name='Imtihon sanasi')),
                ('exam_start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('exam_end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Imtihon davomiyligi (daqiqa)')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('passing_score', models.PositiveIntegerField(verbose_name="O'tish bali (foizda, masalan: 70)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratgan')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Ball (foizda)')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name="Noto'g'ri javoblar")),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('result_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('passed', "O'tdi"), ('failed', "O'tmadi")], default='pending', max_length=10, verbose_name='Holat')),
                ('questions_data', models.JSONField(blank=True, default=dict, verbose_name='Savollar va javoblar (JSON)')),
                ('user_answers', models.JSONField(blank=True, default=dict, verbose_name='Foydalanuvchi javoblari (JSON)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Xodim')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='Imtihon')),
            ],
            options={
                'verbose_name': 'Imtihon natijasi',
                'verbose_name_plural': 'Imtihon natijalari',
                'unique_together': {('exam', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/generated/', verbose_name='Sertifikat fayli')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Sertifikat raqami')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Xodim')),
                ('exam_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.examresult', verbose_name='Imtihon natijasi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=500, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=500, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar bazasi',
            },
        ),
        migrations.CreateModel(
            name='RuleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Hujjat nomi')),
                ('description', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
                ('pdf_file', models.FileField(upload_to='documents/', verbose_name='PDF fayl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim yuklagan')),
            ],
            options={
                'verbose_name': 'Qoida hujjati',
                'verbose_name_plural': 'Qoida hujjatlari',
            },
        ),
    ]
